[[plugins]]
repo = 'vim-denops/denops.vim'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-around'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
on_source = 'ddc.vim'

[[plugins]]
repo = 'ddc-nvim-lsp'
on_source = 'ddc.vim'

[[plugins]]
repo = 'Shougo/ddc.vim'
on_event = 'InsertEnter'
depends = ['depends.vim', 'ddc-around', 'ddc-matcher_head']
hook_add = '''
  call ddc#custom#patch_global('sources', ['around', 'nvim-lsp'])
  call ddc#custom#patch_global('sourceOptions', {
    \ '_': {
    \   'matchers': ['matcher_head'],
    \   'sorters': ['sorter_rank'],
    \   'around': {'mark':'A'}
    \   'nvim-lsp': {
    \   'mark': 'L',
    \   'forceCompletionPattern': '\.\w*|:\w*|->\w*',
    \   }
    \ }})
  call ddc#enable()
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_post_source = '''
  autocmd FileType go nmap <Space>gr <Plug>(go-run)
  autocmd FileType go nmap <Space>gb <Plug>(go-build)
  autocmd FileType go nmap <Space>gt <Plug>(go-test)
  autocmd FileType go nmap <Space>gc <Plug>(go-coverage)
  autocmd FileType go nmap <Space>gd <Plug>(go-doc)
  autocmd FileType go nmap <Space>gi <Plug>(go-import)
  autocmd FileType go nmap <Space>gm <Plug>(go-implements)
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  let g:go_highlight_functions = 1
  let g:go_highlight_build_constraints = 1
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'vim-syntastic/syntastic'
on_ft = ['python']
hook_post_source = '''
  let g:syntastic_python_checkers = ['flake8', 'pyflakes', 'pep8']
'''

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['dockerfile']
