[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'mhinz/vim-startify'
hook_post_source = '''
  let g:startify_skiplist = [
      \ '.cache/.*', 
      \ ]
  let g:startify_bookmarks = [ 
      \ '~/.vimrc', 
      \ '~/.aws/credentials', 
      \ '~/.aws/config' 
      \ ]
  let g:startify_lists = [
      \ { 'header': ['   Bookmarks'],      'type': 'bookmarks' },
      \ { 'header': ['   MRU'],            'type': 'files' },
      \ { 'header': ['   MRU '. getcwd()], 'type': 'dir' },
      \ { 'header': ['   Sessions'],       'type': 'sessions' },
      \ ]
'''

[[plugins]]
repo = 'dracula/vim'
hook_add = '''
  colorscheme dracula
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_post_source = '''
  let g:gitgutter_sign_added = '+'
  let g:gitgutter_sign_modified = '->'
  let g:gitgutter_sign_removed = '-'

  function! MyGitGutter()
    if ! exists('*GitGutterGetHunkSummary')
        \ || ! get(g:, 'gitgutter_enabled', 0)
        \ || winwidth('.') <= 90
      return '---'
    endif
    let symbols = [
        \ g:gitgutter_sign_added . ' ',
        \ g:gitgutter_sign_modified . ' ',
        \ g:gitgutter_sign_removed . ' '
        \ ]
    let hunks = GitGutterGetHunkSummary()
    let ret = []
    for i in [0, 1, 2]
      if hunks[i] > 0
        call add(ret, symbols[i] . hunks[i])
      endif
    endfor
    return join(ret, ' ')
  endfunction
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
depends = ['Shougo/unite.vim']
hook_post_source = '''
  let g:vimfiler_as_default_explorer = 1
  let g:vimfiler_enable_auto_cd = 1
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_post_source = '''
  let g:indentLine_setColors = 0
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['vim-gitgutter', 'dracula']
hook_add = '''
  set noshowmode
  let g:lightline = {
      \ 'colorscheme': 'dracula',
      \ 'mode_map': {'c': 'NORMAL'},
      \ 'active': {
      \   'left': [
      \     ['mode', 'paste'],
      \     ['gitgutter', 'filename'],
      \   ],
      \   'right': [
      \     ['lineinfo', 'syntastic'],
      \     ['percent'],
      \     ['charcode', 'fileformat', 'fileencoding', 'filetype'],
      \   ]
      \ },
      \ 'component_function': {
      \   'gitgutter': 'MyGitGutter',
      \ },
      \}
'''

# LSP (Language Server Protocol)
[[plugins]]
repo = 'prabirshrestha/vim-lsp'

# LSP settings
[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets']
hook_add = '''
imap <C-l>     <Plug>(neosnippet_expand_or_jump)
smap <C-l>     <Plug>(neosnippet_expand_or_jump)
xmap <C-l>     <Plug>(neosnippet_expand_target)
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

